### PR TITLE
In `FieldSearchHelper` skip protected or private fields that cannot be read by `Unsafe`

### PR DESCRIPTION
**Pull request by eupp**

### CODE REVIEW

**Comment by eupp** [comment]
Should fix #340

**Review by ndkoval — CHANGES_REQUESTED** [review]

**Comment by ndkoval** [comment]
@eupp could you please check the red builds?

**Comment by eupp** [comment]
It turns out `Class::isHidden()` and `Class::isRecord()` were introduced only in Java 15. 
So I rollbacked to the exception-catching solution.

**Comment by ndkoval** [comment]
@eupp, please add a comment to the code explaining the logic.

**Comment by eupp** [comment]
> @eupp, please add a comment to the code explaining the logic.

@ndkoval, done

**Review by ndkoval — APPROVED** [review]

**Pull request merged**
