### PR TITLE
Writeside Migration (Test PR)

### PR DESCRIPTION
**Pull request by Quattro8**

### CODE REVIEW

**Comment by ndkoval** [comment]
Hi @Quattro8, thanks for the WriterSide update! Is it possible to check that these changes do not break the documentation before merging the PR?

**Comment by Quattro8** [comment]
@ndkoval hi, it is just the test PR.

We've already checked the docs itself (we built them and publish to the staging). Also it is possible to use my fork to open the migrated docs in WRS and check all what you need

**Comment by Quattro8** [comment]
@ndkoval just ignore it) it contains a list of changes that will be applied in the migration day (25 of September)

**Comment by ndkoval** [comment]
This is a test PR. The changes are merged under #385.

**Pull request closed without merging**
